config/routes.rb
SampleApp::Application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :password_resets

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/theme', to: 'static_pages#theme', via: 'get'
  match '/reset-password', to: 'password_resets#new', as: 'reset_password', via: 'get'
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email_param)
    if user
      user.send_password_reset
      flash[:info] = "An email has been sent to your account with password reset instructions"
      redirect_to root_url
    else
      flash.now[:warning] = "Unable to find user with email #{params[:email]}"
      render 'new'
    end
  end

  def edit
     begin
      @user = User.find_by!(password_reset_token: params[:id])
     rescue
       flash[:warning] = "Sorry, something went wrong!"
       redirect_to root_url
     end
  end

  def update

    @user = User.find_by!(password_reset_token: params[:id])

    if @user
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]
    end
    if @user.password_reset_sent_at < 4.hours.ago
      flash[:warning] = "Password reset has expired, please re-submit your email"
      redirect_to new_password_reset_path
    elsif @user.update_attributes(password: @user.password, password_confirmation: @user.password_confirmation)
      sign_in(@user, "on")
      flash[:success] = "Your password has been reset!"
      redirect_to root_url
    else
      render "edit"
    end
  end

private

    def email_param
      params.permit(:email)
    end

end

app/views/password_resets/edit.html.erb
<div class="container">

  <% if @user.errors.any? %>
    <div class="alert alert-danger">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>



  <div class="form-signin">
    <h2 class="form-signin-heading">Reset your password</h2>

    <%= form_for @user, :url => password_reset_url(params[:id]) do |f| %>
      <div class="form-group">
        <label class="control-label" for="password">Password</label>
        <%= f.password_field :password, :placeholder => "Password", :class => "form-control" %>
      </div>
      <div class="form-group">
        <label class="control-label" for="password">Password confirmation</label>
        <%= f.password_field :password_confirmation, :placeholder => "Confirm Password", :class => "form-control" %>
      </div>
      <%= f.submit "Update Password", class: "btn btn-lg btn-primary btn-block" %>
    <% end %>

  </div>
</div>

app/views/password_resets/new.html.erb
<% provide(:title, "Reset Password") %>

<div class="container">

  <div class="form-signin">
    <h2 class="form-signin-heading">Reset Password</h2>
    <%= form_tag password_resets_path,:id => "password_reset-form", role: "form", :method => :post do %>
    <div class="form-group">
      <label class="control-label" for="email">Email Address</label>
      <%= email_field_tag :email, params[:email], :placeholder => "Email", :class => "form-control", :id => "email" %>
    </div>
      <%= submit_tag "Reset your password", class: "btn btn-lg btn-primary btn-block" %>
      <% end %>
  </div>
</div> <!-- /container -->